### PR TITLE
Stable Custom Elements in Safari! 🎉

### PR DESCRIPTION
**Pull request by abdonrd**
screen shot 2017-03-28 at 12 54 46 pm

### CODE REVIEW

**Comment by stramel** [comment]
Any chance you want to publish this as a separate element? :D

**Comment by samuelli** [comment]
@stramel: The whole table?

**Comment by stramel** [comment]
@samuelli Yeah, would love to embed this into my internal catalog for all my co-workers.

**Comment by abdonrd** [comment]
@samuelli is the deployment to master manual? In Travis I only see the staging.

**Comment by samuelli** [comment]
@stramel: I'll take a look, no guarantees though!

@abdonrd: yep, for two reasons. a) needs to be manually verified before/after deployment and b) since our code is split across 4 different 'services', we need to manually select which ones to deploy.

I've deployed it now; thanks for sending the PR!

**Comment by samuelli** [comment]
@stramel: https://www.webcomponents.org/element/samuelli/wc-browser-table

**Comment by stramel** [comment]
@samuelli Thank you!!! ❤️

**Pull request merged**
