### PR TITLE
Add links to corresponding accepted specifications

### PR DESCRIPTION
**Pull request by TimvdLippe**
I am always googling my way to the correct location of the specifications. Seems like a nice fit for this table to also provide a link to the correct specification location.

### CODE REVIEW

**Comment by abdonrd** [comment]
Should we update the links?

I think we can use always the latest editor's drafts, since it has the most up-to-date information. Also, they have the links to the latest published versions.

The latest editor's drafts:
- https://w3c.github.io/webcomponents/spec/custom/
- https://w3c.github.io/webcomponents/spec/shadow/ (waiting https://github.com/w3c/webcomponents/issues/661)
- https://w3c.github.io/webcomponents/spec/imports/

The latest published versions:
- https://www.w3.org/TR/custom-elements/
- https://www.w3.org/TR/shadow-dom/
- https://www.w3.org/TR/html-imports/

**Comment by TimvdLippe** [comment]
I am okay with that as well. Don't really mind to which they link 😄

**Comment by samuelli** [comment]
Either seems fine to me!

**Comment by abdonrd** [comment]
PR at https://github.com/webcomponents/webcomponents.org/pull/1097

**Pull request merged**
