### PR TITLE
Add note about 'latest' version bug in collections

### PR DESCRIPTION
**Pull request by seaneking**
From https://github.com/webcomponents/webcomponents.org/issues/910

### CODE REVIEW

**Comment by samuelli** [comment]
@dstockwell: does version range even work for collections? Or do you have to specify GitHub repo?

**Comment by samuelli** [comment]
Let's restrict it to explicitly owner/repo. The issue isn't really about bower, but we use that owner/repo to look up the owner/repo and create that link. `bower install` doesn't actually get run on collections.

**Comment by seaneking** [comment]
In that case I'd suggest just rephrasing the line about adding bower deps, rather than adding a note (because they're a special kind of bower dep, really). Feel free to close this PR and I can submit a new one if you like

**Comment by samuelli** [comment]
Sounds good.

**Pull request closed without merging**
